### ISSUE TITLE
CampJS VII local network things

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vii#3]
Let us know what kind of resources you would like to be available offline (as in within the CampJS commune), currently on the teams radar / wishlist:
- NPM (might not be the whole thing, but it we’ll see how we go): https://docs.npmjs.com/misc/registry
- stackoverflow extract (not sure about having a site to be able to browse the data): https://archive.org/details/stackexchange
- gitlab (for local project sharing)
- dokku machine (for showing stuff off)

Installers for things:
- node

**Comment by damncabbage** [comment]
https://github.com/facebook/flow/releases/download/v0.25.0/flow-linux64-v0.25.0.zip
https://github.com/facebook/flow/releases/download/v0.25.0/flow-osx-v0.25.0.zip
(The npm `flow-bin` package goes and fetches these at install-time, sadly.)

**Comment by DamonOehlman** [comment]
@damncabbage Good point - I wonder how many other packages have those kind of additional offsite dependencies.  I guess anything that is using [`node-pre-gyp`](https://www.npmjs.com/package/node-pre-gyp) is a likely candidate...

**Comment by AndreiRailean** [comment]
Also curvytron is a must: http://www.curvytron.com/

**Comment by SomeoneWeird** [comment]
Also probably xcode + VS installers
