### ISSUE TITLE
Stuff to Pickup on the way to CampJS VII

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vii#4]
Since it's in Sydney and I have a ute, I'll be picking up a few things on the way to the event (and quite likely doing multiple trips).  Here's the list of stuff that I know about:
1. Audio Gear
   _from [DJ Warehouse Sydney](https://www.google.com/maps/dir//2+George+Street,+Leichhardt+NSW+2040/@-33.8896257,151.0783661,12z/data=!3m1!4b1!4m8!4m7!1m0!1m5!1m1!1s0x6b12b00c307d69d5:0x64bf757844ab4c43!2m2!1d151.1484062!2d-33.8896455!8s0ALHuxZqQbrp8A-0rP-8SBnztVZutC-Y_FwChd3d3cuZGp3YXJlaG91c2UuY29tLmF1LxIdaHR0cDovL3d3dy5kandhcmVob3VzZS5jb20uYXUaO0RKIFdhcmVob3VzZSBIaXJlIFN5ZG5leSAtIEVhc3kgREogRXF1aXBtZW50IEhpcmUgYW5kIFNldHVwIiJTb3VuZCAmIExpZ2h0aW5nLCBQYXJ0aWVzICYgRXZlbnRzKgA)_
2. Firewood
   _from somwhere_
3. Non-alcoholic beverages
   _from [Woolworths Hornsby](https://www.woolworths.com.au/Shop/StoreLocator/NSW-Hornsby-1294)  (probably)_
4. Alcoholic beverages that folks have **pre-purchased online for BYO**
   _from [Dan Murphy's](https://www.danmurphys.com.au/Stores/NSW-Hornsby-1725) (probably)_

**Comment by AndreiRailean** [comment]
To keep the fire going all night like we did at RailsCamp, you'll need lots of firewood. Finding some wood to burn shouldn't be a problem if we plan ahead and collect it during the day.

At RailsCamp we managed to find enough at night (every night), but it's better when you don't have to scout in darkness.

**Comment by damncabbage** [comment]
As one of the people who did a bunch of scrounging to get the wood at Railscamp: please, just bring some.

**Comment by DamonOehlman** [comment]
I'll make a stop here then at some point and pick up some bags :)

http://herfoswoodshed.com.au/herfosshop/

**Comment by DamonOehlman** [comment]
Or not :(

Pickup service is only offered on Saturdays, it's a min 1000kg order otherwise 😆

**Comment by lukebrooker** [comment]
If I ever need firewood, usually check Gumtree. I can usually find some for free or next to nothing. Might be some near you?
