### ISSUE TITLE
Final Reminder Email Things

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vii#5]
Please add comments below for things you think people need to know about in the final email (2 days out) before CampJS :)

**Comment by DamonOehlman** [comment]
Some of the things I've mentioned in the #campjs channel on viewsource, so far:

Stuff in this list (we'll pull it apart a bit) and give you a more concise list in the email
- https://sportandrecreation.nsw.gov.au/facilities/communityprograms/info

Also, here's some things which cover how I tend to prepare my machine before going offline:
- https://gist.github.com/DamonOehlman/19b4025d08c93d0c890c2c33339ae262

Also, it should be noted that @digitalcraft has been doing a lot of prep work to bring down a pile of stuff we might for offline use, so don't panic too much about that.  Though generally the more self sufficient you are, the more fun you will have.

**Comment by DamonOehlman** [comment]
And something about water taxis - leaving at unscheduled times, etc.

**Comment by SomeoneWeird** [comment]
Reiterate travel? train times? etc

**Comment by halhenke** [comment]
Yeah - a rough idea of which train people would need to catch to make the 2pm/5pm ferries would be great. 

Of the trains from Central seems like one might be cutting it too close and the other involves an hour wait.

**Comment by DamonOehlman** [comment]
It's a bit tight in some cases re the trains, I think we'll try to get the ferries to leave 10 minutes after the hour...
