### ISSUE TITLE
Saturday Afternoon Lightning Talks

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vii#6]
Still need to make the schedule tweaks so the website reflects this, but if you have something you think you'd like to talk about maybe drop a comment here :)

**Comment by fraserxu** [comment]
**Service Worker in action**  (lightning talk)

Campjs could be a great example telling us developers the importance of offline user experience. I will give a demo of how I use `serviceworker` and `manifest.json` as a start point to make my Jekyll powered blog website into an offline friendly app. Along with a couple of examples of production website using serviceworker and some useful resources and links for further study.
